spring:
  datasource:
    url: jdbc:mysql://localhost:3306/uninote_db?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: youngjd00020172!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  secret: your_very_strong_and_secret_key_32_characters_long_min
  expiration: 86400000 # 24시간 (ms)
